### PR TITLE
fix: reject bare record struct names used as values

### LINKED ISSUE #146: Uninstantiated structs are allowed to be compiled in place of an instantiated struct
It seems that uninstantiated structs are allowed to be used in place of an actual instantiated value of that struct, like in the example below:
```rs
struct Coord { x: int, y: int }

fn add_coords(c1: Coord, c2: Coord) -> Coord {
  Coord { x: c1.x + c2.x, y: c1.y + c2.y }
}

fn main() {
  let c1: Coord = Coord { x: 1, y: 1 }
  let c2: Coord = Coord // this line shouldn't compile, but does
  add_coords(c1, c2)
}
```
This results in an error in the resulting Go output of `./main.go:26:8: Coord (type) is not an expression`, since the output that is generated is the following:
```go
package main

import "fmt"

type Coord struct {
	x int
	y int
}

func (c Coord) String() string {
	return fmt.Sprintf("Coord { x: %v, y: %v }", c.x, c.y)
}

func add_coords(c1, c2 Coord) Coord {
	return Coord{
		x: c1.x + c2.x,
		y: c1.y + c2.y,
	}
}

func main() {
	c1 := Coord{
		x: 1,
		y: 1,
	}
	c2 := Coord // error here
	add_coords(c1, c2)
}
```

### PR DESCRIPTION
**Pull request by ivov**
Fix #146

### CODE REVIEW

File: crates/semantics/src/checker/mod.rs [hunk 1]
```diff
@@ -111,6 +111,9 @@ pub(crate) struct InferenceState {
     /// etc.).  Used to reject `Err(x)?`/`None?` in value positions where they
     /// can never produce a value.
     pub in_subexpression: bool,
+    /// Suppresses record-struct-as-value errors when the struct name is a type
+    /// qualifier in a method chain (e.g. `lib.Point` in `lib.Point.sum`).
+    pub dot_access_base: bool,
```
Comment (ivov) [inline crates/semantics/src/checker/mod.rs:116]: Temporary, planning a refactor to reduce inference state.
